version: 1

before:
    hooks:
        - go mod tidy

builds:
    - binary: mycli
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin

archives:
    - format: tar.gz
      format_overrides:
          - goos: windows
            format: zip

brews:
    - name: mycli
      description: "A simple CLI for testing purposes"
      homepage: "https://github.com/jerilseb/my-cli"
      repository:
          owner: jerilseb
          name: homebrew-tap
      commit_author:
          name: goreleaserbot
          email: bot@goreleaser.com
